(() => {"use strict";
const VERSION="2.0.0"; const GOOGLE_SCRIPT_URL="https://script.google.com/macros/s/AKfycbzDsAjeKrqIUjZD77vSTX4CcwWjJBfG1vNnVJSPfLs6QLwl2vUuwMWAl_SwPd3htrg1/exec"; const STORAGE_KEY="ilztalbahn.v2.records"; const TRAIN_KEY="ilztalbahn.v2.lastTrain"; const LEGACY_KEYS=["fahrgaeste","ilztalbahn_sheets","ilztalbahn_optional_ticket","ilztalbahn"];
const stations=["Passau Hbf","Tiefenbach","Fischhaus","Kalteneck","Fürsteneck","Neuhausmühle","Röhrnbach","Waldkirchen","Freyung"]; const aliases={"Neuhäusermühle":"Neuhausmühle"}; const stationIndex=Object.fromEntries(stations.map((n,i)=>[n,i])); let records=[]; let syncRunning=false; const $=id=>document.getElementById(id);
function normalizeStation(v){return aliases[v]||v} function createId(){return crypto&&typeof crypto.randomUUID==="function"?crypto.randomUUID():Date.now().toString(36)+"-"+Math.random().toString(36).slice(2)}
function calculateDirection(a,b){const i=stationIndex[normalizeStation(a)],j=stationIndex[normalizeStation(b)];return !Number.isInteger(i)||!Number.isInteger(j)||i===j?"":i<j?"Passau → Freyung":"Freyung → Passau"}
function normalizeRecord(r){const e=normalizeStation(r.einstieg||r.start||""),a=normalizeStation(r.ausstieg||r.end||r.ziel||"");return{id:r.id||createId(),datum:r.datum||new Date().toISOString().slice(0,10),zugnummer:String(r.zugnummer||r.zug||"").trim(),ticket:r.ticket||r.deutschlandticket||"Nicht angegeben",anzahl:Math.max(1,parseInt(r.anzahl??1,10)||1),einstieg:e,ausstieg:a,richtung:r.richtung||calculateDirection(e,a),zeit:r.zeit||r.time||new Date().toISOString(),geraet:r.geraet||navigator.userAgent.slice(0,100),synced:Boolean(r.synced??r.sync)}}
function migrate(){if(localStorage.getItem(STORAGE_KEY))return;for(const k of LEGACY_KEYS){const v=localStorage.getItem(k);if(!v)continue;try{const p=JSON.parse(v);if(Array.isArray(p)&&p.length){localStorage.setItem(STORAGE_KEY,JSON.stringify(p.map(normalizeRecord)));return}}catch(e){console.warn(e)}}}
function load(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");records=Array.isArray(p)?p.map(normalizeRecord):[]}catch(e){records=[]}} function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records))}
function fillStations(){for(const id of ["einstieg","ausstieg"]){const s=$(id);s.innerHTML='<option value="">Bitte wählen</option>';stations.forEach(n=>s.add(new Option(n,n)))}}
function initial(){$("datum").value=new Date().toISOString().slice(0,10);$("zugnummer").value=localStorage.getItem(TRAIN_KEY)||""}
function preview(){const d=calculateDirection($("einstieg").value,$("ausstieg").value);$("directionPreview").textContent=d?"Richtung: "+d:"Richtung wird automatisch berechnet."}
function changeCount(d){const i=$("anzahl"),v=parseInt(i.value||"1",10)||1;i.value=Math.max(1,v+d)}
function validate(){const datum=$("datum").value,zugnummer=$("zugnummer").value.trim(),einstieg=$("einstieg").value,ausstieg=$("ausstieg").value,anzahl=parseInt($("anzahl").value,10);if(!datum||!zugnummer||!einstieg||!ausstieg){alert("Bitte Datum, Zugnummer, Einstieg und Ausstieg ausfüllen.");return null}if(einstieg===ausstieg){alert("Einstieg und Ausstieg dürfen nicht identisch sein.");return null}if(!Number.isInteger(anzahl)||anzahl<1){alert("Bitte eine gültige Anzahl eingeben.");return null}return{id:createId(),datum,zugnummer,ticket:$("ticket").value||"Nicht angegeben",anzahl,einstieg,ausstieg,richtung:calculateDirection(einstieg,ausstieg),zeit:new Date().toISOString(),geraet:navigator.userAgent.slice(0,100),synced:false}}
function savePassenger(){const r=validate();if(!r)return;records.push(r);persist();localStorage.setItem(TRAIN_KEY,r.zugnummer);$("status").textContent=`${r.anzahl} Fahrgast/Fahrgäste gespeichert: ${r.einstieg} → ${r.ausstieg}`;$("anzahl").value="1";$("einstieg").value="";$("ausstieg").value="";$("ticket").value="";preview();renderAll();syncPending()}
function sumTicket(t){return records.reduce((s,r)=>r.ticket===t?s+r.anzahl:s,0)} function dashboard(){$("gesamt").textContent=records.reduce((s,r)=>s+r.anzahl,0);$("dticket").textContent=sumTicket("Deutschlandticket");$("bticket").textContent=sumTicket("Bayernticket");$("gutiticket").textContent=sumTicket("Guti Ticket");$("fahrrad").textContent=sumTicket("Fahrrad");$("unknownTicket").textContent=sumTicket("Nicht angegeben")}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function trainStats(){const m=new Map();records.forEach(r=>m.set(r.zugnummer||"Ohne Zugnummer",(m.get(r.zugnummer||"Ohne Zugnummer")||0)+r.anzahl));let h="<table><thead><tr><th>Zugnummer</th><th>Fahrgäste</th></tr></thead><tbody>";[...m.entries()].sort((a,b)=>a[0].localeCompare(b[0],"de")).forEach(([z,n])=>h+=`<tr><td>${esc(z)}</td><td>${n}</td></tr>`);if(!m.size)h+='<tr><td colspan="2">Noch keine Daten</td></tr>';$("trainStats").innerHTML=h+"</tbody></table>"}
function od(){const m=stations.map(()=>stations.map(()=>0));records.forEach(r=>{const i=stationIndex[normalizeStation(r.einstieg)],j=stationIndex[normalizeStation(r.ausstieg)];if(Number.isInteger(i)&&Number.isInteger(j))m[i][j]+=r.anzahl});let h='<table><thead><tr><th>Einstieg \ Ausstieg</th>';stations.forEach(s=>h+=`<th>${esc(s)}</th>`);h+='</tr></thead><tbody>';stations.forEach((s,i)=>{h+=`<tr><th>${esc(s)}</th>`;stations.forEach((_,j)=>h+=`<td>${m[i][j]}</td>`);h+='</tr>'});$("odmatrix").innerHTML=h+'</tbody></table>'}
function sections(){const c=new Array(stations.length-1).fill(0);records.forEach(r=>{const a=stationIndex[normalizeStation(r.einstieg)],b=stationIndex[normalizeStation(r.ausstieg)];if(!Number.isInteger(a)||!Number.isInteger(b)||a===b)return;for(let i=Math.min(a,b);i<Math.max(a,b);i++)c[i]+=r.anzahl});let h='<table><thead><tr><th>Streckenabschnitt</th><th>Fahrgäste</th></tr></thead><tbody>';c.forEach((n,i)=>h+=`<tr><td>${esc(stations[i])} – ${esc(stations[i+1])}</td><td>${n}</td></tr>`);$("sections").innerHTML=h+'</tbody></table>'}
function syncStatus(msg=""){const p=records.filter(r=>!r.synced).length,e=$("syncStatus");e.className="sync-status";if(msg){e.textContent=msg;e.classList.add(msg.includes("Fehler")?"error":"pending");return}if(!navigator.onLine){e.textContent=`Offline · ${p} Datensatz/Datensätze warten`;e.classList.add("pending")}else if(p>0){e.textContent=`Online · ${p} Datensatz/Datensätze werden synchronisiert`;e.classList.add("pending")}else{e.textContent="Alle lokalen Daten sind synchronisiert";e.classList.add("ok")}}
async function syncPending(){if(syncRunning||!navigator.onLine){syncStatus();return}const p=records.filter(r=>!r.synced);if(!p.length){syncStatus();return}syncRunning=true;syncStatus();for(const r of p){try{await fetch(GOOGLE_SCRIPT_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(r)});r.synced=true;persist()}catch(e){syncStatus("Fehler bei der Synchronisation · später neuer Versuch");break}}syncRunning=false;persist();renderAll()}
function csvCell(v){return '"'+String(v??"").replaceAll('"','""')+'"'} function exportCSV(){const rows=[["ID","Datum","Zugnummer","Fahrscheinart","Anzahl","Einstieg","Ausstieg","Richtung","Zeit","Synchronisiert"],...records.map(r=>[r.id,r.datum,r.zugnummer,r.ticket,r.anzahl,r.einstieg,r.ausstieg,r.richtung,r.zeit,r.synced?"Ja":"Nein"])];const csv="﻿"+rows.map(x=>x.map(csvCell).join(";")).join("
"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`Ilztalbahn_Fahrgaeste_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function clearData(){if(!confirm("Wirklich alle lokal gespeicherten Datensätze löschen?"))return;records=[];persist();$("status").textContent="Lokale Daten wurden gelöscht.";renderAll()}
function renderAll(){dashboard();trainStats();od();sections();syncStatus()} function events(){$("minusButton").addEventListener("click",()=>changeCount(-1));$("plusButton").addEventListener("click",()=>changeCount(1));$("saveButton").addEventListener("click",savePassenger);$("exportButton").addEventListener("click",exportCSV);$("clearButton").addEventListener("click",clearData);$("einstieg").addEventListener("change",preview);$("ausstieg").addEventListener("change",preview);$("zugnummer").addEventListener("change",()=>localStorage.setItem(TRAIN_KEY,$("zugnummer").value.trim()));window.addEventListener("online",syncPending);window.addEventListener("offline",syncStatus)}
async function start(){migrate();load();fillStations();initial();events();renderAll();preview();if("serviceWorker" in navigator){try{await navigator.serviceWorker.register("service-worker.js?v="+VERSION)}catch(e){console.warn(e)}}syncPending()} document.addEventListener("DOMContentLoaded",start);
})();